#!/bin/bash

############### LITTLE CONTEXT ##################
# its irritating and slow to create a pull request through UI
# works with macos x out of box just place it inside ~/bin/ and add ~/bin to your $PATH
# replace open with xdg-open if using with linux

############### USAGE ###########################

# git pr target_user target_repo target_branch source_user source_branch[optional]
# git pr coverfox rblog pre-master arun6582 [yourbranch(option)]
# yourbranch is option in case you want to create a pr with current active branch
# its no brainer actually but faster than ui


if [ -z "$5" ]
then 
    branch=`git rev-parse --abbrev-ref HEAD`
else
    branch=$5
fi

if [ -z "$branch" ]
then 
    echo "Please provide branch name"
    exit
fi

url="https://github.com/$1/$2"

open "$url/compare/$3...$4:$branch"
